visitors.config:
  type: config_object
  label: 'Visitors Settings'
  mapping:
    chart_height:
      type: integer
      label: 'chart height'
    chart_width:
      type: integer
      label: 'chart width'
    exclude_user1:
      type: boolean
      label: 'exclude user1'
    excluded_roles:
      label: 'excluded roles from logs'
      type: sequence
      sequence:
        type: string
        label: 'role'
    flush_log_timer:
      label: 'log retention time'
      type: integer
    items_per_page:
      type: integer
      label: 'items per page'
    show_last_registered_user:
      type: boolean
      label: 'show last registered user'
    show_published_nodes:
      type: boolean
      label: 'show published nodes'
    show_registered_users_count:
      type: boolean
      label: 'show count of registered users'
    show_since_date:
      type: boolean
      label: 'show registration date'
    show_total_visitors:
      type: boolean
      label: 'show total visitors'
    show_unique_visitor:
      type: boolean
      label: 'show unique visitors'
    show_user_ip:
      type: boolean
      label: 'show user ip'
    start_count_total_visitors:
      type: integer
      label: 'initial total visitors count'
    theme:
      type: string
      label: 'visitors active theme'

block.settings.visitors_block:
  type: block_settings
  label: 'Visitors block configuration'
  mapping:
    show_last_registered_user:
      type: boolean
      label: 'show last registered user'
    show_published_nodes:
      type: boolean
      label: 'show published nodes'
    show_registered_users_count:
      type: boolean
      label: 'show count of registered users'
    show_since_date:
      type: boolean
      label: 'show registration date'
    show_total_visitors:
      type: boolean
      label: 'show total visitors'
    show_unique_visitor:
      type: boolean
      label: 'show unique visitors'
    show_user_ip:
      type: boolean
      label: 'show user ip'
