filemime.settings:
  type: config_object
  label: 'File MIME settings'
  mapping:
    file:
      type: string
      label: 'Local mime.types file path'
    types:
      type: string
      label: 'Custom MIME type mappings'
